#pragma once

#include "plugin/plugin_type.hpp"

#include <memory>
#include <vector>

namespace phosphor::logging::plugin
{

/**
 * @class Descriptor
 *
 * @brief Base descriptor used to create plugins.
 *
 * Descriptors are generated by producers and consumed
 * by PluginManager to create runtime plugin instances.
 */
class Descriptor
{
  public:
    Descriptor() = default;
    Descriptor(const Descriptor&) = default;
    Descriptor(Descriptor&&) = default;
    Descriptor& operator=(const Descriptor&) = delete;
    Descriptor& operator=(Descriptor&&) = default;
    virtual ~Descriptor() = default;

    /**
     * @brief Return descriptor type.
     *
     * @return Plugin type identifier.
     */
    virtual Type type() const = 0;
};

using DescriptorPtr = std::unique_ptr<Descriptor>;
using DescriptorList = std::vector<DescriptorPtr>;

} // namespace phosphor::logging::plugin
