#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
------------------------------------------------------------
THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY

Generated by : generate_lut.py
STRICT MODE: Enforces presence of arg1 level
------------------------------------------------------------
"""

import argparse
import json
from datetime import datetime
from pathlib import Path


# ==========================================================
# CLI
# ==========================================================
def parse_args():
    parser = argparse.ArgumentParser(description="Generate constexpr LUT")
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    return parser.parse_args()


# ==========================================================
# Validation
# ==========================================================
def is_leaf(node):
    return (
        isinstance(node, dict)
        and "afid" in node
        and "originOfCondition" in node
    )


def validate_leaf(node, path):
    if not isinstance(node["afid"], int):
        raise ValueError(f"afid must be int at {path}")
    if not isinstance(node["originOfCondition"], str):
        raise ValueError(f"originOfCondition must be string at {path}")


def validate_structure(lookup):
    for reg, reg_val in lookup.items():
        for msg, msg_val in reg_val.items():
            if is_leaf(msg_val):
                raise ValueError(
                    f"Invalid LUT: Missing arg1 level at {reg}->{msg}"
                )


def validate_node(node, path="root"):
    if is_leaf(node):
        validate_leaf(node, path)
        return

    if not isinstance(node, dict):
        raise ValueError(f"Invalid node at {path}")

    for k, v in node.items():
        validate_node(v, f"{path}->{k}")


def validate_json(data):
    if "lookup" not in data:
        raise ValueError("Missing 'lookup' section")

    validate_structure(data["lookup"])  # ✅ strict enforcement
    validate_node(data["lookup"])


# ==========================================================
# Helpers
# ==========================================================
def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def split_patterns(key):
    return [p.strip() for p in key.split("|")]


# ==========================================================
# Arg usage detection (correct depth)
# ==========================================================
def detect_arg_usage(lookup):
    used = set()

    for reg_val in lookup.values():
        for msg_val in reg_val.values():
            collect_args(msg_val, depth=1, used=used)

    return used


def collect_args(node, depth, used):
    if is_leaf(node):
        return

    used.add(depth)

    for v in node.values():
        collect_args(v, depth + 1, used)


# ==========================================================
# Pattern dedup
# ==========================================================
class PatternPool:
    def __init__(self):
        self.pool = {}

    def get(self, patterns):
        key = tuple(sorted(patterns))
        if key not in self.pool:
            self.pool[key] = f"p_{len(self.pool)}"
        return self.pool[key]

    def emit(self, out):
        for patterns, name in sorted(self.pool.items(), key=lambda x: x[1]):
            out.write(f"constexpr std::string_view {name}[] = {{\n")
            for p in patterns:
                out.write(f'    "{escape(p)}",\n')
            out.write("};\n\n")


# ==========================================================
# Code generation
# ==========================================================
def generate(data, out_path, input_file):
    lookup = data["lookup"]
    fallback = int(data.get("fallthrough_afid", 0))

    pool = PatternPool()

    # Collect patterns
    def collect(node):
        if is_leaf(node):
            return
        for k, v in sorted(node.items()):
            pool.get(split_patterns(k))
            collect(v)

    collect(lookup)

    used_args = detect_arg_usage(lookup)

    with open(out_path, "w") as out:

        # ===== Header =====
        out.write("// SPDX-License-Identifier: Apache-2.0\n")
        out.write(
            "// ------------------------------------------------------------\n"
        )
        out.write("// THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY\n")
        out.write("//\n")
        out.write("// Generated by : generate_lut.py\n")
        out.write(f"// Input file : {input_file}\n")
        out.write(f"// Build time : {datetime.utcnow()}\n")
        out.write(
            "// ------------------------------------------------------------\n\n"
        )

        out.write("#pragma once\n\n")
        out.write("#include <string_view>\n\n")

        out.write(
            "struct AFIDResult { int afid; std::string_view origin; };\n\n"
        )

        # ===== Match functions =====
        out.write(
            "constexpr bool matchPattern(std::string_view s, std::string_view p){\n"
        )
        out.write('    if(p=="*") return true;\n')
        out.write("    auto i=p.find('*');\n")
        out.write("    if(i==std::string_view::npos) return s==p;\n")
        out.write("    auto pre=p.substr(0,i);\n")
        out.write("    auto suf=p.substr(i+1);\n")
        out.write(
            "    if(!pre.empty() && s.substr(0, pre.size())!=pre) return false;\n"
        )
        out.write(
            "    if(!suf.empty() && s.substr(s.size()-suf.size())!=suf) return false;\n"
        )
        out.write("    return true;\n")
        out.write("}\n\n")

        out.write("template<size_t N>\n")
        out.write(
            "constexpr bool matchAny(std::string_view v,const std::string_view(&a)[N]){\n"
        )
        out.write("    for(auto p:a) if(matchPattern(v,p)) return true;\n")
        out.write("    return false;\n")
        out.write("}\n\n")

        pool.emit(out)

        # ===== API =====
        out.write("constexpr AFIDResult lookupAFID(\n")
        out.write("    std::string_view reg,\n")
        out.write("    std::string_view msg,\n")
        out.write("    std::string_view arg1,\n")
        out.write("    std::string_view arg2,\n")
        out.write("    std::string_view arg3,\n")
        out.write("    std::string_view arg4)\n")
        out.write("{\n")

        # Compile-time flags
        for i in range(1, 5):
            flag = "true" if i in used_args else "false"
            out.write(f"    constexpr bool USE_ARG{i} = {flag};\n")

        out.write("\n")

        # Strict validation
        out.write(
            '    static_assert(USE_ARG1, "Invalid LUT: arg1 required");\n\n'
        )

        # Avoid unused warnings
        for i in range(1, 5):
            out.write(f"    if constexpr (!USE_ARG{i}) (void)arg{i};\n")

        out.write("\n")

        # Emit tree
        def emit(node, indent, depth):
            ind = " " * indent

            if is_leaf(node):
                out.write(
                    f'{ind}return {{ {node["afid"]}, "{escape(node["originOfCondition"])}" }};\n'
                )
                return

            arg_map = {1: "arg1", 2: "arg2", 3: "arg3", 4: "arg4"}
            arg = arg_map.get(depth, "arg4")

            for k, v in sorted(node.items()):
                arr = pool.get(split_patterns(k))

                if k == "*":
                    out.write(f"{ind}if(true){{\n")
                else:
                    out.write(f"{ind}if(matchAny({arg},{arr})){{\n")

                emit(v, indent + 4, depth + 1)
                out.write(f"{ind}}}\n")

        for reg, regv in sorted(lookup.items()):
            out.write(f'    if(reg=="{escape(reg)}"){{\n')

            for msg, msgv in sorted(regv.items()):
                out.write(f'        if(msg=="{escape(msg)}"){{\n')

                emit(msgv, 12, 1)

                out.write("        }\n")

            out.write("    }\n")

        out.write(f'    return {{ {fallback}, "" }};\n')
        out.write("}\n")


# ==========================================================
# MAIN
# ==========================================================
if __name__ == "__main__":
    args = parse_args()

    with open(args.input) as f:
        data = json.load(f)

    validate_json(data)

    out_file = Path(args.output)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    generate(data, out_file, args.input)

    print(f"[AEL] LUT generated: {out_file}")
